# This file contains the values obtained by the calibration package
# Results are written in the form that they can be directly sent to a static_transform_publisher node
# Recall its usage use static_transform_publisher x y z qx qy qz qw frame_id child_frame_id  period(milliseconds)
translation: [0.242524, 0.224674, 1.4823]
rotation: [0.262603, 0.733288, -0.574824, 0.250811]
frame_id: camera_rgb_optical_frame
child_frame_id: world
